services:
  - type: web
    name: ecotrip-backend
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    region: oregon
    plan: free
    branch: main
    healthCheckPath: /swagger/index.html
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://*:10000
      - key: ConnectionStrings__DefaultConnection
        value: Server=localhost;Database=EcoTripDb;Trusted_Connection=true;TrustServerCertificate=true;
        # Nota: Esta cadena de conexión deberás cambiarla por tu base de datos real
